version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: cachefy-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  memcached:
    image: memcached:1.6-alpine
    container_name: cachefy-memcached
    ports:
      - "11211:11211"
    command: memcached -m 64 -v
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  redis-data:
    driver: local

networks:
  default:
    name: cachefy-network